hassanhabib/The-Standard

Services/Foundations/Foundations.md

FOUNDATION: common scenarios for foundation services 

---

2. Services/2.0 Foundations/2.0 Foundations.md

Update 2.0 Foundations.md

---

2. Services/2.1 Processings/2.1 Processings.md
2. Services/2.2 Orchestrations/2.2 Orchestrations.md

Orchestrations

---

README.md

Replaced introcution with introduction

Fixed a spelling bug in the first line

---

2. Services/2.3 Orchestrations/2.3 Orchestrations.md
README.md

DOCUMENTATION: Update Wrapping & Unwrapping Section on Dependency Exceptions

---

0. Introduction/0.0 Purposing, Modeling & Simulation.md

DOCUMENTATION: Fix Spelling Gaol to Goal

---

2. Services/2.1 Foundations/2.1 Foundations.md
2. Services/2.2 Processings/2.2 Processings.md

CODE RUB: Removes Typo (Excists -> Exists)

---

2. Services/2.1 Foundations/2.1 Foundations.md

Trying to express what I think this sentence meant.

CODE RUB: Upsertable Exceptions - Attempt to express what was intended

---

1. Brokers/1. Brokers.md

CODE RUB: Fix StorageBroker.Students snippet param

---

0. Introduction/0.2 Principles.md

Update 0.2 Principles.md

---

0. Introduction/0.0 The Theory.md

CODE RUB: Edited using Grammarly
Edited spelling, punctuation, and grammar errors and removed extraneous words where appropriate without changing the meaning.

CODE RUB: Editing The Theory.md

---

0. Introduction/0.1 Purposing, Modeling & Simulation.md

CODE RUB: Edited using Grammarly
Edited spelling, punctuation, and grammar errors and removed extraneous words where appropriate without changing the meaning.

CODE RUB: Edited Purposing, Modeling and Simulation

---

1. Brokers/1. Brokers.md

CODE RUB: edit the "Brokers" chapter using Grammarly

CODE RUB: edit brokers chapter

---

2. Services/2.2 Processings/2.2 Processings.md

CODE RUB: Update 2.2 Processings.md

---

2. Services/2.1 Foundations/2.1 Foundations.md

CODE RUB: Update 2.1 Foundations.md

---

1. Brokers/1. Brokers.md

Replaced namespace OtripleS.Web.Api.Brokers.Storage with namespace OtripleS.Web.Api.Brokers.Storages

CODERUB: Corrected namespace.

---

1. Brokers/1. Brokers.md

Replaced OtripleS.Web.Api.Brokers.Storage with namespace OtripleS.Web.Api.Brokers.Storages

CODE RUB: Resolved namespace for IStorageBroker.Students.cs

---

2. Services/2.1 Foundations/2.1 Foundations.md

CODE RUB: Typo fix

---

2. Services/2.1 Foundations/2.1 Foundations.md

Changed this.storageBroker instance to this.storageBrokerMock. this.loggingBroker instance to this.loggingBrokerMock.

CODE RUB: Corrected sample test code and typo fix

---

README.md

Added link to The Standard YouTube Playlist.

Updated Other Resources

---

2. Services/2.1 Foundations/2.1 Foundations.md

Update 2.1 Foundations.md

---

README.md

Updates the version and adds badges

Documentations: Readme Latest Update

---

3. Exposers/3. Exposers.md

CODE RUB: Add Space Between Two Words

---

0. Introduction/0.1 Purposing, Modeling & Simulation.md

Let's talk about these categoris in details:
... reads better as ...
Let's talk about these categories in detail:

CODE RUB: Minor Typo Fix

---

2. Services/2.3 Orchestrations/2.3 Orchestrations.md

Found smal issue in the documentation of Orchestration services while reading.

CODE RUB: Update 2.3 Orchestrations.md

---

2. Services/2.1 Foundations/2.1 Foundations.md

CODE RUB: Switch Statement Is No Longer Used

---

2. Services/2.1 Foundations/2.1 Foundations.md
2. Services/2.3 Orchestrations/2.3 Orchestrations.md
2. Services/2.4 Aggregations/2.4 Aggregations.md
README.md

CODE RUB: Standard Version `v2.10.1` Upgrade

---

2. Services/2. Services.md

There was a typo that says all instead of call.

CODE RUB: typo in 2.0.2.5.0

---

2. Services/2.1 Foundations/2.1 Foundations.md

DOCUMENTATION: Foundations Enhancement

---

0. Introduction/0.2 Principles.md
1. Brokers/1. Brokers.md
1. Brokers/1.8 Broker Provider Abstraction.md
2. Services/2.2 Processings/2.2 Processings.md
2. Services/2.3 Orchestrations/2.3 Orchestrations.md
2. Services/2.4 Aggregations/2.4 Aggregations.md
3. Exposers/3.1 Communication Protocols/3.1.1 RESTful APIs/3.1.1 RESTful APIs.md

Abstraction at the operational levels
Readability over Optimization
Closes: #288
Closes #290

DOCUMENTATION: Upgrade V2.10.3

---

2. Services/2.1 Foundations/2.1 Foundations.md

CODE RUB: Reverts Validation Private Method Asynchronous Abstraction

---

2. Services/2.5 Controllers/2.5 Controllers.md

STANDARD: Controllers v2.11.0

---

.github/workflows/release_pdf.yml

CONFIG: PDF Build Set Uses -> artifact@v4

---

1. Brokers/1. Brokers.md

RELEASES: Private DbSet v2.11.2

---

0. Introduction/0.3 Testimonials.md

DOCUMENTATIONS: Update Testimonial
